// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoWAOhSzoCsRMYXS6pquJlizoJvB-77vs',
    appId: '1:195949054113:web:26638dc9f8615f58ab08e0',
    messagingSenderId: '195949054113',
    projectId: 'demoproject-87d37',
    authDomain: 'demoproject-87d37.firebaseapp.com',
    storageBucket: 'demoproject-87d37.firebasestorage.app',
    measurementId: 'G-FMZ1ERKLKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoWAOhSzoCsRMYXS6pquJlizoJvB-77vs',
    appId: '1:195949054113:android:9d45e43c5b8e5c58ab08e0', // Placeholder if not provided
    messagingSenderId: '195949054113',
    projectId: 'demoproject-87d37',
    storageBucket: 'demoproject-87d37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoWAOhSzoCsRMYXS6pquJlizoJvB-77vs',
    appId: '1:195949054113:ios:6c638dc9f8615f58ab08e0', // Placeholder
    messagingSenderId: '195949054113',
    projectId: 'demoproject-87d37',
    storageBucket: 'demoproject-87d37.firebasestorage.app',
    iosBundleId: 'com.example.blinkiteUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoWAOhSzoCsRMYXS6pquJlizoJvB-77vs',
    appId: '1:195949054113:ios:6c638dc9f8615f58ab08e0',
    messagingSenderId: '195949054113',
    projectId: 'demoproject-87d37',
    storageBucket: 'demoproject-87d37.firebasestorage.app',
    iosBundleId: 'com.example.blinkiteUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoWAOhSzoCsRMYXS6pquJlizoJvB-77vs',
    appId: '1:195949054113:windows:26638dc9f8615f58ab08e0',
    messagingSenderId: '195949054113',
    projectId: 'demoproject-87d37',
    authDomain: 'demoproject-87d37.firebaseapp.com',
    storageBucket: 'demoproject-87d37.firebasestorage.app',
    measurementId: 'G-FMZ1ERKLKB',
  );
}
